Repository OpenMined/SyferText, pull requests merged in 2020-06, with the labels that each got.

#113 Removed explicity maspack registration
  setup.py
  syfertext/__init__.py
  syfertext/pipeline/simple_tagger.py
  syfertext/pipeline/subpipeline.py
  syfertext/tokenizer.py
  syfertext/utils.py
Labels: Priority: 1 - Immediate :fire:, Severity: 1 - Critical :fire:

#67 Lexeme
  syfertext/attrs.py
  syfertext/language.py
  syfertext/lex_attrs.py
  syfertext/lexeme.py
  syfertext/stop_words.py
  syfertext/token.py
  syfertext/tokenizer.py
  syfertext/vectors.py
  syfertext/vocab.py
  tests/local_mode/test_lexeme.py
  tests/local_mode/test_token.py
  tests/local_mode/test_token_attributes.py
  tutorials/Part 0 - (Getting Started) Local Tokenization.ipynb
Labels: Priority: 1 - Immediate :fire:, Severity: 3 - Medium :unamused:, Type: New Feature :heavy_plus_sign:

#114 Added _get_valid_tokens() to Doc and Span
  syfertext/doc.py
  syfertext/pointers/doc_pointer.py
  syfertext/span.py
Labels: Priority: 3 - Medium :unamused:, Status: Investigating :mag:, Status: Review Needed :raising_hand:, Type: Improvement :chart_with_upwards_trend:, Type: Refactor :hammer:

#129 Add support section at README.md
  README.md
Labels: Status: Completed :heavy_check_mark:, Type: Documentation :books:
