Repository OpenMined/SyferText, pull requests merged in 2020-05, with the labels that each got.

#78 Added Span
  syfertext/doc.py
  syfertext/language.py
  syfertext/pipeline/subpipeline.py
  syfertext/pointers/__init__.py
  syfertext/pointers/doc_pointer.py
  syfertext/pointers/span_pointer.py
  syfertext/span.py
  syfertext/token.py
  syfertext/utils.py
  tests/local_mode/test_span.py
Labels: new feature

#80 Added attribute functionality
  syfertext/doc.py
  syfertext/pipeline/subpipeline.py
  syfertext/span.py
  syfertext/token.py
  syfertext/token_exception.py
  tests/local_mode/test_doc.py
  tests/local_mode/test_language.py
Labels: new feature

#87 Add tutorial for SimpleTagger
  tutorials/Part 2 - (Getting Started) Using SimpleTagger.ipynb
Labels: documentation

#50 Added similarity of documents and tokens
  syfertext/doc.py
  syfertext/token.py
  tests/local_mode/test_doc.py
  tests/local_mode/test_token.py
Labels: Priority: 1 - Immediate :fire:, Severity: 4 - Low :sunglasses:, Status: Completed :heavy_check_mark:, Status: Review Needed :raising_hand:, Type: New Feature :heavy_plus_sign:

#108 Prepared support for future syft v0.2.7
  setup.py
  syfertext/__init__.py
  syfertext/doc.py
  syfertext/language.py
  syfertext/pipeline/pointers/subpipeline_pointer.py
  syfertext/pipeline/subpipeline.py
  syfertext/pointers/doc_pointer.py
  syfertext/pointers/span_pointer.py
  syfertext/span.py
  syfertext/token.py
  syfertext/tokenizer.py
  tests/local_mode/test_doc.py
Labels: Priority: 1 - Immediate :fire:, Severity: 2 - High :cold_sweat:, Status: Completed :heavy_check_mark:, Status: Review Needed :raising_hand:
