Repository OpenMined/SyferText, pull requests merged in 2020-07, with the labels that each got.

#104 Pypi publish
  .github/workflows/publish.yml
  setup.cfg
  setup.py
Labels: Priority: 2 - High :cold_sweat:, Severity: 4 - Low :sunglasses:, Status: Review Needed :raising_hand:

#132 Replace Numpy arrays by torch tensors
  syfertext/doc.py
  syfertext/lexeme.py
  syfertext/pointers/doc_pointer.py
  syfertext/token.py
  syfertext/vectors.py
  tests/local_mode/test_doc.py
  tests/local_mode/test_language.py
  tests/local_mode/test_lexeme.py
  tests/local_mode/test_token.py
  tests/local_mode/test_token_attributes.py
Labels: Priority: 4 - Low :sunglasses:, Severity: 4 - Low :sunglasses:, Type: Improvement :chart_with_upwards_trend:

#115 Removed garbage_collect_data from __init__() functions
  syfertext/doc.py
  syfertext/pipeline/pointers/subpipeline_pointer.py
  syfertext/pipeline/subpipeline.py
  syfertext/pointers/doc_pointer.py
  syfertext/pointers/span_pointer.py
  syfertext/span.py
Labels: Priority: 3 - Medium :unamused:, Severity: 3 - Medium :unamused:, Status: Review Needed :raising_hand:, Type: Improvement :chart_with_upwards_trend:

#146 Update README.md
  README.md
Labels: Type: Documentation :books:, syfertext 0.1.0

#150 Added support for loading vectors to Vocab
  syfertext/language.py
  syfertext/pipeline/subpipeline.py
  syfertext/vectors.py
  syfertext/vocab.py
Labels: Status: Completed :heavy_check_mark:, Status: Review Needed :raising_hand:, syfertext 0.1.0

#117 Update Readme
  README.md
Labels: Priority: 3 - Medium :unamused:, Severity: 4 - Low :sunglasses:, Type: Documentation :books:, syfertext 0.1.0

#154 update syft version pypi release
  setup.py
Labels: Type: Refactor :hammer:
