Repository OpenMined/SyferText, pull requests merged in 2021-01, with the labels that each got.

#191 Implementing caching when loading from PyGrid nodes
  setup.py
  syfertext/__init__.py
  syfertext/pipeline/single_label_classifier.py
  syfertext/tokenizer.py
  syfertext/utils.py
  syfertext/vocab.py
  tests/distributed_mode/test_single_label_classifier.py
  tests/local_mode/test_cache.py
Labels: Priority: 2 - High :cold_sweat:, Severity: 3 - Medium :unamused:, Status: In Progress :star2:, syfertext 0.1.0

#195 added pricon2020 tutorial notebook
  setup.py
  tutorials/usecases/pricon2020_demo_virtual_live_run.ipynb
Labels: syfertext 0.1.0

#160 Medical text classification (usecase tutorial)
  .gitignore
  README.md
  tutorials/usecases/UC02 - Medical Text Classification (Secure Training).ipynb
  tutorials/usecases/art/mtsamples/accuracy.png
  tutorials/usecases/art/mtsamples/loss.png
Labels: Priority: 3 - Medium :unamused:, Severity: 4 - Low :sunglasses:, Status: Review Needed :raising_hand:

#192 Add pipeline parsing tests
  tests/local_mode/test_pipeline.py
Labels: Status: Review Needed :raising_hand:
